[context]
name = "expand-tilde"
version = "0.2.0"
url = "https://github.com/nekitdev/expand-tilde"

[formats]
title = "[{{version}}]({{url}}/tree/v{{version}}) ({{date}})"
fragment = "{{content}} ([#{{id}}]({{url}}/pull/{{id}}))"
